# Generated by Django 3.2.25 on 2024-10-16 19:01

from django.db import migrations
import phonenumbers


def make_pure_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        number = flat.owners_phonenumber
        
        if number.startswith('8'):
            number = '+7' + number[1:]

        number = phonenumbers.parse(number, 'RU')
        formatted_number = phonenumbers.format_number(
            number, 
            phonenumbers.PhoneNumberFormat.E164
        )
        
        flat.owner_pure_phone = formatted_number
        flat.save()
            
    
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(make_pure_phone_numbers)
    ]
