# Generated by Django 3.2.25 on 2024-10-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20241016_2201'),
        ('property', '0010_auto_20241016_2244'),
    ]

    operations = [
    ]
