# Generated by Django 3.2.25 on 2024-10-16 20:47

from django.db import migrations


def add_owners(apps, scema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        Owner.objects.get_or_create(
            owner=flat.owner, 
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(add_owners)
    ]